### ISSUE TITLE
submodules

### ISSUE THREAD

**Issue by norayr** [vgratian/smog#1]
hello,

i was trying to build [lagrange](https://codeberg.org/skyjake/lagrange) and realized we cannot do, as suggested `git clone --recursive --branch release https://git.skyjake.fi/gemini/lagrange` with smog.

instead i went to the `pkg` directory, found downloaded git repo, and made

`git submodule init`
`git submodule update`

thank you.

**Comment by vgratian** [comment]
this should be easy to implement for `smog add`, I think we can use the flag `-r` for recursive cloning.

what I am not entirely sure how to handle are `smog sync` and `smog update`.

**Comment by vgratian** [comment]
do you think `smog update` should also update submodules by default? or only when you use the same `-r` (recursive) flag?

**Comment by norayr** [comment]
i think it should. because we have no way to know if it needs a more modern submodule or not.

**Comment by vgratian** [comment]
btw, you don't need to go to find the pkg directory manually, just run:

```bash
cd `smog lagrange path`
```

**Comment by norayr** [comment]
great!

**Comment by vgratian** [comment]
submodules should be recognized by now (https://github.com/vgratian/smog/commit/9bb3445f18cdbf5497dbdc81db16c301e9f83a86) .

short explanation:
    - use `smog add URL -r` to clone submodules as well
    - if `-r` is not provided and smog detects `.gitmodules`, it will ask what to do
    - if you run `smog update PKG`, submodules will be updated as well

warnings:
    - not tested well, so use at your own risk
    - when updating, smog will not take care of code changes in submodules

**Comment by vgratian** [comment]
please re-open if you are not satisified
